[versions]
# Libraries
kotlin = "2.1.0"
asm = "5.2"
guava = "24.1.1-jre"
gson = "2.8.6"
jetbrainsAnnotations = "24.1.0"

# Mods
forgelin = "2.1.0.0"
mixinBooter = "9.1"
modularui = "2.5.0-rc4"
codeChickenLib = "3.2.3.358"
groovyScript = "1.2.0-hotfix1"
craftTweaker2 = "1.12-4.1.20.700"
ctm = "2915363" # 1.0.2.31
ae2ExtendedLife = "6302098" # 0.56.7
jei = "4.16.1.302"
theOneProbe = "2667280" # 1.4.28
smoothFonts = "3944565" # 2.1.4
betterQuestingUnofficial = "5875712" # 4.2.6

# Plugins
ideaExt = "1.1.7"
retrofuturaGradle = "1.3.27"
curseGradle = "1.4.0"
dokka = "1.9.10"
shadow = "7.1.2"
spotless = "8.1.0"

[libraries]
# Libraries
asm                      = { group = "org.ow2.asm",                   name = "asm-debug-all",                     version.ref = "asm"                      }
guava                    = { group = "com.google.guava",              name = "guava",                             version.ref = "guava"                    }
gson                     = { group = "com.google.code.gson",          name = "gson",                              version.ref = "gson"                     }
jetbrainsAnnotations     = { group = "org.jetbrains",                 name = "annotations",                       version.ref = "jetbrainsAnnotations"     }

# Mods
forgelin                 = { group = "io.github.chaosunity.forgelin", name = "Forgelin-Continuous",               version.ref = "forgelin"                 }
mixinBooter              = { group = "zone.rong",                     name = "mixinbooter",                       version.ref = "mixinBooter"              }
modularui                = { group = "com.cleanroommc",               name = "modularui",                         version.ref = "modularui"                }
codeChickenLib           = { group = "codechicken",                   name = "codechickenlib",                    version.ref = "codeChickenLib"           }
groovyScript             = { group = "com.cleanroommc",               name = "groovyscript",                      version.ref = "groovyScript"             }
craftTweaker2            = { group = "CraftTweaker2",                 name = "CraftTweaker2-MC1120-Main",         version.ref = "craftTweaker2"            }
ctm                      = { group = "curse.maven",                   name = "ctm-267602",                        version.ref = "ctm"                      }
ae2ExtendedLife          = { group = "curse.maven",                   name = "ae2-extended-life-570458",          version.ref = "ae2ExtendedLife"          }
jei                      = { group = "mezz.jei",                      name = "jei_1.12.2",                        version.ref = "jei"                      }
theOneProbe              = { group = "curse.maven",                   name = "top-245211",                        version.ref = "theOneProbe"              }
smoothFonts              = { group = "curse.maven",                   name = "smooth-font-285742",                version.ref = "smoothFonts"              }
betterQuestingUnofficial = { group = "curse.maven",                   name = "better-questing-unofficial-629629", version.ref = "betterQuestingUnofficial" }

[plugins]
ideaExt           = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExt"           }
retrofuturaGradle = { id = "com.gtnewhorizons.retrofuturagradle",  version.ref = "retrofuturaGradle" }
curseGradle       = { id = "com.matthewprenger.cursegradle",       version.ref = "curseGradle"       }
dokka             = { id = "org.jetbrains.dokka",                  version.ref = "dokka"             }
shadow            = { id = "com.github.johnrengelman.shadow",      version.ref = "shadow"            }
spotless          = { id = "com.diffplug.spotless",                version.ref = "spotless"}